# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iLnqDnqeU39Ut6H8yc0jQLvhk5claR2m
"""

# Speed of light in a vacuum (m/s)
c = 299792458

def gamma(v):
    # Calculates the Lorentz factor (gamma)
    return 1 / np.sqrt(1 - (v/c)**2)

def time_dilation(t0, v):
    # Calculates time dilation (t')
    return gamma(v) * t0

def length_contraction(L0, v):
    # Calculates length contraction (L')
    return L0 / gamma(v)

def lorentz_transform(x, t, v):
    # Performs the Lorentz transformation for spacetime coordinates (x, t)
    g = gamma(v)

    # Transformed spatial coordinate
    xp = g * (x - v*t)
    # Transformed temporal coordinate
    tp = g * (t - v*x/c**2)

    return xp, tp

import numpy as np
import matplotlib.pyplot as plt

# Calculate velocities from 0 to just below the speed of light
v_values = np.linspace(0, 0.999 * c, 500)

# Calculate Lorentz factor for each velocity
gamma_values = [gamma(v) for v in v_values]

# Create the plot
plt.figure(figsize=(10, 6))
# Plot Lorentz factor vs. velocity
plt.plot(v_values / c, gamma_values)
# Set x-axis label
plt.xlabel('Velocity (v/c)')
# Set y-axis label
plt.ylabel('Lorentz Factor (gamma)')
# Set plot title
plt.title('Lorentz Factor vs. Velocity')
# Add grid
plt.grid(True)
# Set y-axis limits
plt.ylim(0, 10)
# Mark the speed of light on the x-axis
plt.axvline(x=1, color='r', linestyle='--', label='Speed of Light (c)')
# Display legend
plt.legend()
# Show the plot
plt.show()

import numpy as np
import matplotlib.pyplot as plt

c = 299792458 # Speed of light

def gamma(v):
    # Calculates the Lorentz factor
    return 1 / np.sqrt(1 - (v/c)**2)

def time_dilation(t0, v):
    # Calculates time-dilated time
    return gamma(v) * t0

# Generate a range of velocities from 0 to just below c
v_values = np.linspace(0, 0.999 * c, 500)

# Calculate time-dilated values for a proper time of 20 units
time_values = [time_dilation(20, v) for v in v_values]

plt.figure(figsize=(10, 6))
# Plot velocity (as a fraction of c) vs. dilated time
plt.plot(v_values / c, time_values)
plt.xlabel('Velocity (v/c)') # X-axis label
plt.ylabel('Dilated Time (t′) for t0 = 20') # Y-axis label
plt.title('Time Dilation vs. Velocity') # Plot title
plt.grid(True) # Add grid
plt.ylim(0, 100) # Set Y-axis limits
plt.axvline(x=1, color='r', linestyle='--', label='Speed of Light (c)') # Mark speed of light
plt.legend() # Display legend
plt.show() # Show the plot

import numpy as np # Import NumPy for numerical operations
import matplotlib.pyplot as plt # Import Matplotlib for plotting

c = 299792458 # Define the speed of light

def gamma(v):
    # Calculates the Lorentz factor
    return 1 / np.sqrt(1 - (v/c)**2)

def length_contraction(L0, v):
    # Calculates the contracted length
    return L0 / gamma(v)

# Generate a range of velocities from 0 to just below c
v_values = np.linspace(0, 0.999 * c, 500)

L0 = 10 # Define the original length
# Calculate contracted lengths for each velocity
contracted_lengths = [length_contraction(L0, v) for v in v_values]

# Create a new figure for the plot
plt.figure(figsize=(10, 6))
# Plot velocity (as a fraction of c) vs. contracted length
plt.plot(v_values / c, contracted_lengths)
plt.xlabel('Velocity (v/c)') # Set X-axis label
plt.ylabel('Contracted Length (L′) for L0 = 10') # Set Y-axis label
plt.title('Length Contraction vs. Velocity') # Set plot title
plt.grid(True) # Add a grid to the plot
plt.ylim(0, L0 * 1.1) # Set Y-axis limits
plt.axvline(x=1, color='r', linestyle='--', label='Speed of Light (c)') # Mark speed of light on the X-axis
plt.axhline(y=L0, color='gray', linestyle=':', label='Original Length (L0)') # Mark original length on the Y-axis
plt.legend() # Display the legend
plt.show() # Show the plot

import numpy as np
import matplotlib.pyplot as plt

# Constants
c = 299792458  # Speed of light
u = 0.80 * c  # Velocity of the object in frame S

# Range of angles in frame S (0 to 180 degrees)
theta_deg = np.linspace(0, 180, 500)
theta_rad = np.radians(theta_deg)

# Relative velocities of frame S' (beta = v/c)
betas = [0.1, 0.4, 0.6, 0.8, 0.95]

plt.figure(figsize=(10, 6))

# Iterate through different relative velocities for frame S'
for beta in betas:
    v = beta * c
    gamma = 1 / np.sqrt(1 - beta**2)

    # Transformation components for calculating transformed angle
    num = u * np.sin(theta_rad) * np.sqrt(1 - beta**2)
    den = u * np.cos(theta_rad) - v

    # Calculate transformed angle using arctan2 for correct quadrant handling
    theta_prime_rad = np.arctan2(num, den)
    theta_prime_deg = np.degrees(theta_prime_rad)

    # Adjust transformed angles to be within 0 to 180 degrees for plotting
    theta_prime_deg = np.where(theta_prime_deg < 0, theta_prime_deg + 360, theta_prime_deg)

    # Plot the transformed angle for the current beta
    plt.plot(theta_deg, theta_prime_deg, label=f'v/c = {beta}')

# Reference line (Classical case where observed angle equals original angle)
plt.plot(theta_deg, theta_deg, 'k--', alpha=0.5, label='Classical (v=0)')

# Plot customization
plt.title(f'Relativistic Angle Transformation for Object Velocity u = {u/c:.2f}c')
plt.xlabel('Angle in Frame S (θ) [degrees]')
plt.ylabel("Observed Angle in Frame S' (θ') [degrees]")
plt.xlim(0, 180)
plt.ylim(0, 180)
plt.legend()
plt.grid(True, linestyle=':', alpha=0.6)
plt.show()

import numpy as np
import matplotlib.pyplot as plt


c = 299792458

def gamma(v_val):
    if v_val >= c:
        return np.inf
    return 1 / np.sqrt(1 - (v_val/c)**2)

def relativistic_velocity_addition(u_vec_s, v_relative):
    ux_s, uy_s, uz_s = u_vec_s
    v = v_relative
    denominator = (1 - ux_s * v / c**2)
    if denominator == 0:
        return np.inf, np.inf, np.inf
    gamma_v = gamma(v)
    ux_prime = (ux_s - v) / denominator
    uy_prime = uy_s / (gamma_v * denominator)
    uz_prime = uz_s / (gamma_v * denominator)
    return ux_prime, uy_prime, uz_prime

plt.figure(figsize=(10, 6))


initial_angles_deg = np.linspace(0, 360, 100)
initial_angles_rad = np.radians(initial_angles_deg)
transformed_angles_rad = []
v_relative_plot = 0.6 * c
u_mag_plot = 0.8 * c

for angle_s_rad in initial_angles_rad:
    ux_s = u_mag_plot * np.cos(angle_s_rad)
    uy_s = u_mag_plot * np.sin(angle_s_rad)
    uz_s = 0

    ux_prime, uy_prime, _ = relativistic_velocity_addition((ux_s, uy_s, uz_s), v_relative_plot)
    transformed_angles_rad.append(np.arctan2(uy_prime, ux_prime))

plt.plot(initial_angles_deg, np.degrees(transformed_angles_rad), label=f'v_relative = {v_relative_plot/c:.2f}c')
plt.plot(initial_angles_deg, initial_angles_deg, linestyle='--', color='gray', label='No change (Classical)')
plt.xlabel('Initial Angle in S (degrees)')
plt.ylabel("Transformed Angle in S' (degrees)")
plt.title(f'Relativistic Angle Transformation for Object Velocity |u| = {u_mag_plot/c:.2f}c')
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

"""### Plotting Velocity Transformation (1D)

This plot demonstrates how a velocity `u` observed in frame S transforms to `u'` in frame S' (moving at a fixed relative velocity `v` with respect to S, along the x-axis). The dashed line represents the classical velocity addition ($u' = u - v$). Notice how the relativistic curve approaches `c` asymptotically.
"""

This plot demonstrates how a velocity u observed in frame S transforms to u' in frame S' (moving at a fixed relative velocity v with respect to S, along the x-axis). The dashed line represents the classical velocity addition ( $u'=u-v$ ). Notice how the relativistic curve approaches c asymptotically.

import numpy as np
import matplotlib.pyplot as plt

c = 299792458

def gamma(v_val):
    if v_val >= c:
        return np.inf
    return 1 / np.sqrt(1 - (v_val/c)**2)

def relativistic_velocity_addition(u_vec_s, v_relative):
    ux_s, uy_s, uz_s = u_vec_s
    v = v_relative
    denominator = (1 - ux_s * v / c**2)
    if denominator == 0:
        return np.inf, np.inf, np.inf
    gamma_v = gamma(v)
    ux_prime = (ux_s - v) / denominator
    uy_prime = uy_s / (gamma_v * denominator)
    uz_prime = uz_s / (gamma_v * denominator)
    return ux_prime, uy_prime, uz_prime

# v_relative is the velocity of frame S' with respect to S
v_relative = 0.5 * c

# u_x_s_values is the velocity of an object in frame S along the x-axis
u_x_s_values = np.linspace(-0.999 * c, 0.999 * c, 500)

transformed_u_x_prime_values = []
classical_u_x_prime_values = []

for u_x_s in u_x_s_values:
    # Relativistic transformation
    ux_prime, _, _ = relativistic_velocity_addition((u_x_s, 0, 0), v_relative)
    transformed_u_x_prime_values.append(ux_prime)

    # Classical transformation
    classical_u_x_prime_values.append(u_x_s - v_relative)

plt.figure(figsize=(10, 6))
plt.plot(u_x_s_values / c, np.array(transformed_u_x_prime_values) / c, label='Relativistic Transformation')
plt.plot(u_x_s_values / c, np.array(classical_u_x_prime_values) / c, linestyle='--', color='gray', label='Classical Transformation')

plt.xlabel('Object Velocity in S (u/c)')
plt.ylabel(f"Object Velocity in S' (u'/c) for v_relative = {v_relative/c:.2f}c")
plt.title('Relativistic vs. Classical Velocity Transformation (1D)')
plt.grid(True)
plt.axhline(y=1, color='red', linestyle=':', label='c')
plt.axhline(y=-1, color='red', linestyle=':')
plt.legend()
plt.ylim(-1.2, 1.2) # Set y-axis limits to clearly show c and -c
plt.tight_layout()
plt.show()



import numpy as np
import matplotlib.pyplot as plt

c = 299792458

def gamma(v):
    return 1 / np.sqrt(1 - (v/c)**2)

def lorentz_transform(x, t, v):
    g = gamma(v)

    xp = g * (x - v*t)
    tp = g * (t - v*x/c**2)

    return xp, tp

x_values = np.linspace(-10, 10, 500)
t = 1
v = 0.8 * c

x_prime_values = [lorentz_transform(x, t, v)[0] for x in x_values]

plt.figure(figsize=(10, 6))
plt.plot(x_values, x_prime_values)
plt.xlabel('Original Spatial Coordinate (x)')
plt.ylabel(f"Transformed Spatial Coordinate (x') at v={v/c:.2f}c, t={t}s")
plt.title('Lorentz Transformation: x versus x\'')
plt.grid(True)
plt.axvline(x=0, color='gray', linestyle='--')
plt.axhline(y=0, color='gray', linestyle='--')
plt.show()